# Generated by Django 3.0.4 on 2020-04-02 03:40

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('practice_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendance',
            managers=[
                ('attendance_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
