# Generated by Django 3.0.4 on 2020-04-02 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practice_api', '0002_auto_20200402_0940'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='attendance',
            managers=[
            ],
        ),
    ]
